name: my_ear_app
description: "Communication app for hearing impaired"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  tflite_flutter: ^0.11.0
  vibration: ^3.1.3
  flutter_local_notifications: ^19.0.0
  http: ^1.3.0
  video_player: ^2.8.0
  image_picker: ^1.1.2
  google_ml_kit: ^0.20.0
  camera: ^0.11.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.7
  intl: ^0.20.2

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/therapy_video.mp4
    - assets/images/
    - assets/labels.txt